# Generated by Django 3.1.7 on 2021-11-19 19:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsApp', '0004_auto_20211119_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
